version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: har-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=har_db
    networks:
      - har-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: har-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=har_db
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - CORS_ORIGINS=["http://localhost:5173","http://localhost:80"]
    depends_on:
      - mongodb
    volumes:
      - ./models:/app/models
    networks:
      - har-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: har-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - har-network

volumes:
  mongodb_data:

networks:
  har-network:
    driver: bridge

